language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GC_MALLOC_LIMIT=50000000

rvm:
  - 2.1

services:
  - redis-server

sudo: false

cache: true

before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - bundle exec rake db:migrate

bundler_args: --without development --deployment --retry=3 --jobs=3

script: 'bundle exec rspec && bundle exec rake plugin:spec && bundle exec rake qunit:test'
