language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com
    - RUBY_GC_MALLOC_LIMIT=50000000
  matrix:
    - TRAVIS_NODE_INDEX=0
    - TRAVIS_NODE_INDEX=1

rvm:
  - 2.1

services:
  - redis-server

sudo: false

cache: bundler

before_script:
  - psql -c 'create database discourse_test;' -U postgres
  - bundle exec rake db:migrate

bundler_args: --without development --deployment --retry=3 --jobs=3

script: 'case $TRAVIS_NODE_INDEX in 0) (bundle exec rspec -P "spec/components/**/*_spec.rb" || true ) && (bundle exec rspec -P "spec/controllers/**/*_spec.rb" || true ) && (bundle exec rspec -P "spec/services/**/*_spec.rb" || true ) && (bundle exec rspec -P "spec/jobs/**/*_spec.rb" || true ) && (bundle exec rake plugin:spec || true) ;; 1) (bundle exec rspec -P "spec/models/**/*_spec.rb" || true ) && (bundle exec rspec -P "spec/{mailers,integration,fabricators,serializers,support,helpers,phantom_js,integrity,views}/**/*_spec.rb" || true ) && (bundle exec rake qunit:test || true ) ;; esac'
