defaults: &defaults
  host: <%= ENV['TDDIUM_REDIS_HOST'] %>
  port: <%= ENV['TDDIUM_REDIS_PORT'] %>
  password: <%= ENV['TDDIUM_REDIS_PASSWORD'] %>
  db: <%= ENV['TDDIUM_REDIS_DB'] %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
